# Generated by Django 5.2.1 on 2025-05-19 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('mass', 'Mass'), ('core', 'Core'), ('dream', 'Dream')], max_length=20)),
                ('description', models.TextField()),
                ('eligibility_criteria', models.TextField()),
                ('job_description', models.TextField()),
                ('application_deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
